version: '3'

tasks:
  build:
    desc: "Build the Go application"
    cmds:
      - go build -o bin/api cmd/api/main.go
  
  test:
    desc: "Run Go tests"
    cmds:
      - go test ./...
  
  lint:
    desc: "Run Go linter"
    cmds:
      - golangci-lint run

  run:
    desc: "Run the Go application"
    cmds:
      - go run cmd/api/main.go

  docker-build:
    desc: "Build the Docker image"
    cmds:
      - docker build -t cloud-file-storage:latest .

  docker-compose:
    desc: "Run Docker Compose"
    cmds:
      - docker-compose up --build

  migrate:
    desc: "Run database migrations"
    cmds:
      - ./scripts/migrate.sh

  deploy:
    desc: "Deploy the application"
    cmds:
      - ./scripts/deploy.sh

  clean:
    desc: "Clean up build artifacts and Docker images"
    cmds:
      - rm -rf bin/
      - docker rmi cloud-file-storage:latest
